language: csharp
mono: none
sudo: required
dist: bionic
dotnet: 2.2.105 
solution: solCards.sln
script:
  - dotnet restore
  - dotnet build
  - dotnet test
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1